SRCS	= subject.c

OBJS	= subject.o

CFLAGS	= -Wall -Wextra -Werror

CC		= gcc

NAME	= ft_rush

RM		= rm -f ${NAME}

${NAME}:	${OBJS}

all:		${CC} ${CFLAGS} -o ${NAME} ${SRCS}

clean:
			${RM} ${OBJS} 

fclean: 	clean
			${RM} ${NAME}

