SRCS	= ft_display_file.c

OBJS	= ft_display_file.o

CFLAGS	= -Wall -Wextra -Werror

CC		= gcc

NAME	= ft_display_file

RM		= rm -f ${NAME}

${NAME}:	${OBJS}

all:		${CC} ${CFLAGS} -o ${NAME} ${SRCS}

clean:
			rm -f ${OBJS} 

fclean: 	clean
			rm -f ${NAME}
